name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  CD:
    name: Running CD to build / deploy to Heroku with docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Build Maven
        run: mvn deploy -B
        continue-on-error: true
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "smartwateringpro"
          heroku_email: "tirgani.badreddine96@gmail.com"
          usedocker: true